spring:
  data:
    neo4j:
      uri: bolt://192.168.63.135:7687
      username: neo4j
      password: 123456
# git clone https://github.com/Harries/springboot-demo
# docker run -p 7474:7474 -p 7687:7687 --name neo4j -e NEO4J_apoc_export_file_enabled=true -e NEO4J_apoc_import_file_enabled=true -e NEO4J_apoc_import_file_use__neo4j__config=true -e NEO4J_PLUGINS=\[\"apoc\"\] neo4j:5.21.2