server:
  port: 8083
spring:
  kafka:
    consumer:
      topicName: oven.test.topic
      enable-auto-commit: true
      group-id: applog_1
      auto-offset-reset: latest
      bootstrap-servers: xxx.xxx.xxx.xxx:9092